### ISSUE TITLE
SuperPoint Training Error

### ISSUE THREAD

**Issue by roborocklsm** [rpautrat/SuperPoint#96]
I have trapped training SuperPoint on COCO for some days.
My device:
```
Ubuntu 18.04
RTX 2070
CUDA 9.0
CUDNN 7.0.5/7.5 (both tried)
Tensorflow 1.6/1.8 (both tried)
```

Here's the error I met.

```
...
[08/06/2019 11:39:33 INFO] Start training
2019-08-06 11:39:34.443710: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x55b43faf0220
2019-08-06 11:39:34.849276: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at matrix_inverse_op.cc:191 : Internal: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
2019-08-06 11:39:35.295289: E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-08-06 11:39:35.295372: F tensorflow/core/kernels/conv_ops.cc:717] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
Aborted (core dumped)
```

I have tried search several keywords on Google, but not too much useful information. 

It is wired that CUDA tries to do `matrix_inverse_op`, should it be CPU? Do you have any idea which part of  the code trying to do matrix inverse ops?

**Comment by roborocklsm** [comment]
I tried ` tensorflow 1.12`. It gives more details of error.
```
[08/06/2019 11:54:15 INFO] Start training
2019-08-06 11:54:16.356576: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x55b84ae915f0
2019-08-06 11:54:16.881153: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at matrix_inverse_op.cc:191 : Internal: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
2019-08-06 11:54:17.155246: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-08-06 11:54:17.158088: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-08-06 11:54:17.162477: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-08-06 11:54:17.165185: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
	 [[{{node superpoint/train_tower0/MatrixInverse}} = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](superpoint/train_tower0/Reshape_1)]]
	 [[{{node superpoint/train_tower0/vgg/conv1_1/bn/FusedBatchNorm/_39}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_196_superpoint/train_tower0/vgg/conv1_1/bn/FusedBatchNorm", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment.py", line 150, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 88, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 27, in train
    keep_checkpoints=config.get('keep_checkpoints', 1))
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/base_model.py", line 313, in train
    options=options, run_metadata=run_metadata)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
	 [[node superpoint/train_tower0/MatrixInverse (defined at /media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/homographies.py:232)  = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](superpoint/train_tower0/Reshape_1)]]
	 [[{{node superpoint/train_tower0/vgg/conv1_1/bn/FusedBatchNorm/_39}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_196_superpoint/train_tower0/vgg/conv1_1/bn/FusedBatchNorm", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'superpoint/train_tower0/MatrixInverse', defined at:
  File "experiment.py", line 150, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 88, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 21, in train
    with _init_graph(config) as net:
  File "/home/shl666/.conda/envs/sp/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 72, in _init_graph
    n_gpus=n_gpus, **config['model'])
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/base_model.py", line 122, in __init__
    self._build_graph()
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/base_model.py", line 264, in _build_graph
    self._train_graph(data)
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/base_model.py", line 188, in _train_graph
    data, Mode.TRAIN, self.config['batch_size'])
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/base_model.py", line 159, in _gpu_tower
    loss = self._loss(net_outputs, shards[i], **self.config)
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/super_point.py", line 82, in _loss
    valid_mask=inputs['warped']['valid_mask'], **config)
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/utils.py", line 83, in descriptor_loss
    warped_coord_cells = warp_points(tf.reshape(coord_cells, [-1, 2]), homographies)
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/homographies.py", line 295, in warp_points
    H_inv = tf.transpose(flat2mat(invert_homography(H)))
  File "/media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/homographies.py", line 232, in invert_homography
    return mat2flat(tf.matrix_inverse(flat2mat(H)))
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1041, in matrix_inverse
    "MatrixInverse", input=input, adjoint=adjoint, name=name)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/shl666/.conda/envs/sp/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
	 [[node superpoint/train_tower0/MatrixInverse (defined at /media/shl666/DATA/lift_sp/SuperPoint/superpoint/models/homographies.py:232)  = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](superpoint/train_tower0/Reshape_1)]]
	 [[{{node superpoint/train_tower0/vgg/conv1_1/bn/FusedBatchNorm/_39}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_196_superpoint/train_tower0/vgg/conv1_1/bn/FusedBatchNorm", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```
Just let you know this on the first moment I get it (might help). I would look into it now.

**Comment by roborocklsm** [comment]
Problem solved.

add `with tf.device(/cpu:0)` to all inverse ops. And then add `TF_FORCE_GPU_ALLOW_GROWTH=true` to the `~/.bashrc' then restart the bash file.

**Comment by rpautrat** [comment]
Thanks for posting your solution!

Actually I ran this code with TF 1.7, so there might indeed be compatibility issues with higher versions of tensorflow...

**Comment by xlong0513** [comment]
> Thanks for posting your solution!
> 
> Actually I ran this code with TF 1.7, so there might indeed be compatibility issues with higher versions of tensorflow...

Hi, I met the same question as following,
![Uploading 图片.png…]()
Must i change the version of cudnn?

**Comment by xlong0513** [comment]
> Thanks for posting your solution!
> 
> Actually I ran this code with TF 1.7, so there might indeed be compatibility issues with higher versions of tensorflow...

Hi, I met the same question as follows,
![图片](https://user-images.githubusercontent.com/35829321/68677579-4ee43280-0597-11ea-88ed-c0ea42febe40.png)

Must i change the version of cudnn? Thanks

**Comment by rpautrat** [comment]
Is this the same error? I don't see the link with the previous post...

**Comment by xlong0513** [comment]
> Is this the same error? I don't see the link with the previous post...

Sorry. This is the link of the same question
[https://github.com/rpautrat/SuperPoint/issues/96](url)

**Comment by rpautrat** [comment]
Same error, but for different reasons apparently. Have you tried the fix of roborocklsm just in case?

Otherwise this seems to be a compatibility issue of CuDNN on your machine (runtime version different from compiled one) and it is out of the scope of this project. Consider removing all versions of CuDNN from your machine and starting a clean install.

**Comment by xlong0513** [comment]
OK! Thank u for the reply!

**Comment by yakult98** [comment]
> Problem solved.
> 
> add `with tf.device(/cpu:0)` to all inverse ops. And then add `TF_FORCE_GPU_ALLOW_GROWTH=true` to the `~/.bashrc` then restart the bash file.

Sorry to bother you, I also encountered the similar problem.Could you please explain the solution in detail?Thanks

**Comment by sanmiyom** [comment]
It works for me too.

It does not have to be about inverse ops. It might be something else too. Just perform the problematic ops on CPU with `tf.device(/cpu:0)`.
